### ISSUE TITLE
Install on ubuntu

### ISSUE THREAD

**Issue by terxw** [iandennismiller/gthnk#1]
Is it possible to install it on ubuntu?

**Comment by iandennismiller** [comment]
Yes, it will install, but I have not yet written a cron job that works with Ubuntu.  As a result, the behaviour will not be correct.  Here's what needs to happen:

- a script called bin/install_ubuntu.sh must be created
- the script must copy a customized upstart.conf to /etc/init to start gthnk at bootup
- the script must initialize the upstart job
- the script must install two cron jobs: 1) midnight journal rotation; 2) 9am journal review

As a result, I consider this to be an open issue, still.

**Comment by iandennismiller** [comment]
This now installs on Ubuntu in two ways: either as a python module or as a runnable Docker image.  Please see http://docs.gthnk.com for more.
