### ISSUE TITLE
Accessing gthnk in the browser gives 404

### ISSUE THREAD

**Issue by dylanirlbeck** [iandennismiller/gthnk#5]
As title; using `http://localhost:1620/admin/journal/latest.html` gives me a 404 Not Found error. For context, I just installed Gthnk, wrote a single entry in `~/.gthnk/journal.txt`, and then went to open the link. I can also confirm that Docker seems to be working properly, since running `docker ps` gives me:

```
1cb3a15fadba        iandennismiller/gthnk   "/bin/sh -c 'sudo -i…"   3 minutes ago       Up 3 minutes        0.0.0.0:1620->1620/tcp   gthnk-server
```

**Comment by iandennismiller** [comment]
Thank you for the report! Sorry for the frustration. The problem here is the documentation, not the server. It is now /day/live instead of /admin/journal/latest.html

I'll keep this ticket open until I update the docs. Thank you for the report.

**Comment by iandennismiller** [comment]
Okay - I think I got it.  I'm closing the issue but I'll be happy to reopen as needed.

Can you please double-check the documentation (doing a cache-reload if necessary)?

If it turns out I missed it, can you please provide the URL or file where the broken URLs are?
