### ISSUE TITLE
Why the login screen?

### ISSUE THREAD

**Issue by dylanirlbeck** [iandennismiller/gthnk#6]
As title -- can you elaborate on why you chose to have a login screen? This is more of a UI/UX gripe.

**Comment by iandennismiller** [comment]
That's a really good question, actually.

So the way I run Gthnk, I put it on a server on the home network and I don't want it hanging out completely unprotected. Theoretically, you could even run this on a public-facing site.  So, I put the auth in place to support this.

However, now that you mention it, when running locally there's no purpose to the auth.  It would make onboarding easier, too, to skip it entirely.

Auth is still useful - but perhaps a configuration flag could toggle this.  And perhaps it should even be disabled by default.

A question: are you planning to run on localhost or eventually deploy somewhere?

**Comment by dylanirlbeck** [comment]
Thanks for the response, that reasoning makes sense. I'll second the notion that running locally should not require the auth. 

To answer your question, I'm only planning on running on localhost!

**Comment by kenlefeb** [comment]
As a follow-up, are there instructions for changing the credentials somewhere? If I host this somewhere on the Internet, I'd rather not continue to use the default credentials.

**Comment by iandennismiller** [comment]
Although it's been a little while, I have an update on this issue.  The latest release, gthnk 0.8.x, has removed the user authentication system altogether. There is no login screen.

To answer the question about publicly hosting, I am using a web server to administer credentials now.  Gthnk runs on localhost and the web server runs as a reverse proxy.
